import type { Scenario } from "./types.js";

export const scenarios: readonly Scenario[] = [
  // ---------------------------------------------------------------------------
  // Commerce — cas nominaux
  // ---------------------------------------------------------------------------
  {
    id: "COMM-001",
    domain: "Commerce",
    title: "Ajouter un produit au catalogue",
    intent: "create_product",
    userQuery: "Ajoute le produit Ciment a 12 000 CDF avec un stock de 50 sacs.",
    roles: ["inventory.manager"],
    expectedCapability: "commerce.product.create",
    expectedStatus: "completed",
    expectedOutcome: { name: "Ciment" },
    plannerOutput: {
      capabilityId: "commerce.product.create",
      arguments: { name: "Ciment", price: 12000, stock: 50 },
      confidence: 0.95,
      reason: "L’utilisateur demande d’ajouter un produit avec prix et stock.",
    },
  },
  {
    id: "COMM-002",
    domain: "Commerce",
    title: "Creer une facture",
    intent: "create_invoice",
    userQuery: "Facture 150 000 CDF au client Okapi Logistics.",
    roles: ["cashier", "sales.manager"],
    expectedCapability: "commerce.invoice.create",
    expectedStatus: "completed",
    expectedOutcome: { customerName: "Okapi Logistics" },
    requiredConfirmation: "medium",
    plannerOutput: {
      capabilityId: "commerce.invoice.create",
      arguments: { customerName: "Okapi Logistics", amount: 150000 },
      confidence: 0.92,
      reason: "Creation d’une facture client.",
    },
  },
  {
    id: "COMM-003",
    domain: "Commerce",
    title: "Enregistrer un paiement",
    intent: "record_payment",
    userQuery: "Le client a paye 75 000 CDF sur la facture INV-2025-001.",
    roles: ["cashier", "finance.manager"],
    expectedCapability: "commerce.payment.record",
    expectedStatus: "completed",
    expectedOutcome: { invoiceId: "INV-2025-001" },
    requiredConfirmation: "high",
    plannerOutput: {
      capabilityId: "commerce.payment.record",
      arguments: { invoiceId: "INV-2025-001", amount: 75000 },
      confidence: 0.94,
      reason: "Paiement partiel sur une facture existante.",
    },
  },
  {
    id: "COMM-004",
    domain: "Commerce",
    title: "Consulter le stock",
    intent: "check_stock",
    userQuery: "Combien de sacs de ciment restent en stock ?",
    roles: ["user"],
    expectedCapability: "commerce.inventory.check",
    expectedStatus: "completed",
    expectedOutcome: { productName: "sacs de ciment" },
    plannerOutput: {
      capabilityId: "commerce.inventory.check",
      arguments: { productName: "sacs de ciment" },
      confidence: 0.88,
      reason: "Question sur le stock disponible.",
    },
  },

  // ---------------------------------------------------------------------------
  // Gestion d’entreprise IA — cas nominaux
  // ---------------------------------------------------------------------------
  {
    id: "BIZ-001",
    domain: "Gestion d’entreprise IA",
    title: "Creer un client",
    intent: "create_customer",
    userQuery: "Enregistre le client Jean Mukendi avec l’email jean@example.cd.",
    roles: ["sales.manager"],
    expectedCapability: "business.customer.create",
    expectedStatus: "completed",
    expectedOutcome: { name: "Jean Mukendi" },
    plannerOutput: {
      capabilityId: "business.customer.create",
      arguments: { name: "Jean Mukendi", email: "jean@example.cd" },
      confidence: 0.96,
      reason: "Creation d’une fiche client.",
    },
  },
  {
    id: "BIZ-002",
    domain: "Gestion d’entreprise IA",
    title: "Planifier une tache",
    intent: "schedule_task",
    userQuery: "Planifie une reunion de suivi pour le vendredi 15 aout 2025.",
    roles: ["manager"],
    expectedCapability: "business.task.schedule",
    expectedStatus: "completed",
    expectedOutcome: { title: "reunion de suivi" },
    plannerOutput: {
      capabilityId: "business.task.schedule",
      arguments: { title: "reunion de suivi", dueDate: "2025-08-15T09:00:00Z" },
      confidence: 0.9,
      reason: "Planification d’une tache.",
    },
  },
  {
    id: "BIZ-003",
    domain: "Gestion d’entreprise IA",
    title: "Generer un rapport",
    intent: "generate_report",
    userQuery: "Genere le rapport de ventes du mois de juin 2025.",
    roles: ["manager", "analyst"],
    expectedCapability: "business.report.generate",
    expectedStatus: "completed",
    expectedOutcome: { reportType: "ventes", period: "juin 2025" },
    plannerOutput: {
      capabilityId: "business.report.generate",
      arguments: { reportType: "ventes", period: "juin 2025" },
      confidence: 0.93,
      reason: "Demande de generation de rapport.",
    },
  },

  // ---------------------------------------------------------------------------
  // Forex — cas nominaux
  // ---------------------------------------------------------------------------
  {
    id: "FX-001",
    domain: "Forex",
    title: "Enregistrer une operation de change",
    intent: "record_operation",
    userQuery: "Achete 10 000 USD contre CDF au taux de 2 850.",
    roles: ["forex.trader"],
    expectedCapability: "forex.operation.record",
    expectedStatus: "completed",
    expectedOutcome: { pair: "USD/CDF" },
    requiredConfirmation: "high",
    plannerOutput: {
      capabilityId: "forex.operation.record",
      arguments: { pair: "USD/CDF", amount: 10000, rate: 2850 },
      confidence: 0.95,
      reason: "Operation d’achat de devises.",
    },
  },
  {
    id: "FX-002",
    domain: "Forex",
    title: "Consulter un portefeuille",
    intent: "check_portfolio",
    userQuery: "Quel est mon solde en dollars ?",
    roles: ["user"],
    expectedCapability: "forex.portfolio.check",
    expectedStatus: "completed",
    expectedOutcome: { currency: "USD" },
    plannerOutput: {
      capabilityId: "forex.portfolio.check",
      arguments: { currency: "USD" },
      confidence: 0.87,
      reason: "Question sur le solde d’une devise.",
    },
  },
  {
    id: "FX-003",
    domain: "Forex",
    title: "Generer un rapport de performance",
    intent: "generate_performance_report",
    userQuery: "Genere le rapport P&L Forex du T2 2025.",
    roles: ["forex.manager"],
    expectedCapability: "forex.report.performance",
    expectedStatus: "completed",
    expectedOutcome: { period: "T2 2025" },
    plannerOutput: {
      capabilityId: "forex.report.performance",
      arguments: { period: "T2 2025" },
      confidence: 0.91,
      reason: "Demande de rapport de performance.",
    },
  },

  // ---------------------------------------------------------------------------
  // Tests de raisonnement — ambigu, manquant, permission, confirmation, impossible
  // ---------------------------------------------------------------------------
  {
    id: "REA-001",
    domain: "Raisonnement",
    title: "Intention ambigue",
    intent: "ambiguous_request",
    userQuery: "Traite la transaction.",
    roles: ["cashier", "finance.manager"],
    expectedCapability: "commerce.payment.record",
    expectedStatus: "rejected",
    plannerOutput: {
      capabilityId: "commerce.payment.record",
      arguments: { invoiceId: "unknown", amount: 0 },
      confidence: 0.4,
      reason: "Demande ambigue, manque invoiceId et amount.",
    },
  },
  {
    id: "REA-002",
    domain: "Raisonnement",
    title: "Permission insuffisante",
    intent: "unauthorized_action",
    userQuery: "Ajoute 100 sacs de ciment au stock.",
    roles: ["cashier"],
    expectedCapability: "commerce.product.create",
    expectedStatus: "rejected",
    plannerOutput: {
      capabilityId: "commerce.product.create",
      arguments: { name: "Ciment", price: 12000, stock: 100 },
      confidence: 0.9,
      reason: "Ajout de stock, mais l’utilisateur n’a pas le role requis.",
    },
  },
  {
    id: "REA-003",
    domain: "Raisonnement",
    title: "Action hautement sensible sans confirmation",
    intent: "sensitive_action_unconfirmed",
    userQuery: "Rembourse 500 000 CDF au client Acme Corp.",
    roles: ["finance.manager"],
    expectedCapability: "commerce.payment.record",
    expectedStatus: "rejected",
    plannerOutput: {
      capabilityId: "commerce.payment.record",
      arguments: { invoiceId: "ACME-REF-001", amount: 500000 },
      confidence: 0.97,
      reason: "Paiement/ref sensible sans confirmation explicite.",
    },
  },
  {
    id: "REA-004",
    domain: "Raisonnement",
    title: "Action hautement sensible avec confirmation",
    intent: "sensitive_action_confirmed",
    userQuery: "Confirme le remboursement de 500 000 CDF au client Acme Corp.",
    roles: ["cashier", "finance.manager"],
    expectedCapability: "commerce.payment.record",
    expectedStatus: "completed",
    expectedOutcome: { amountPaid: 500000 },
    requiredConfirmation: "high",
    plannerOutput: {
      capabilityId: "commerce.payment.record",
      arguments: { invoiceId: "ACME-REF-001", amount: 500000 },
      confidence: 0.97,
      reason: "Remboursement confirme par l’utilisateur.",
    },
  },
  {
    id: "REA-005",
    domain: "Raisonnement",
    title: "Demande impossible",
    intent: "impossible_request",
    userQuery: "Vide completement le stock de ciment sans facture.",
    roles: ["inventory.manager"],
    expectedCapability: "commerce.inventory.check",
    expectedStatus: "rejected",
    plannerOutput: {
      capabilityId: "commerce.inventory.check",
      arguments: { productName: "ciment" },
      confidence: 0.3,
      reason: "Aucune capability ne permet de vider le stock sans facture.",
    },
  },
];
